### ISSUE TITLE
It not a function to get the data from adapter.

### ISSUE THREAD

**Issue by Qeveloper** [ironSource/OneAdapter#44]
The OneAdapter  class is not open, and then  I can't get the data from the adapter.   can support  a function to read the data from the adapter?

**Comment by idanatz** [comment]
This is by design.
Ideally, the items (or views) should be stateless and direct logic and state to a presenter or viewmodel.
When working with OneAdapter you care about your models and data and not how they are reflected in the adapter.
The adapter is not exposing its data since there are internal viewholders and logic that is irrelevant to the user.

What is the use case you need to access a specific item in the adapter?
